version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  target-branch: dev
  assignees:
  - keindev
  labels:
  - dependencies
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.27
    - 14.14.28
    - 14.14.29
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
    - 15.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
    - 26.0.22
    - 26.0.23
  - dependency-name: eslint
    versions:
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.2.1
    - 24.3.1
    - 24.3.2
    - 24.3.3
    - 24.3.4
    - 24.3.5
    - 24.3.6
  - dependency-name: ts-jest
    versions:
    - 25.5.1
    - 26.5.3
    - 26.5.4
    - 26.5.5
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 2.34.0
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 2.34.0
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
    - 4.22.0
  - dependency-name: cspell
    versions:
    - 5.3.10
    - 5.3.11
    - 5.3.12
    - 5.3.4
    - 5.3.7
    - 5.3.8
    - 5.3.9
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 6.0.0
  - dependency-name: globby
    versions:
    - 11.0.3
  - dependency-name: stdout-update
    versions:
    - 1.6.4
    - 1.6.5
  - dependency-name: typescript
    versions:
    - 4.2.3
  - dependency-name: "@types/yargs"
    versions:
    - 16.0.0
  - dependency-name: eslint-plugin-import
    versions:
    - 2.22.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: yargs
    versions:
    - 16.2.0
  - dependency-name: prettier
    versions:
    - 2.2.1
  - dependency-name: eslint-config-prettier
    versions:
    - 6.15.0
  - dependency-name: acorn
    versions:
    - 6.4.2
  - dependency-name: lodash
    versions:
    - 4.17.20
    - 4.17.21
  - dependency-name: jest
    versions:
    - 26.0.1
  - dependency-name: eslint-config-airbnb-base
    versions:
    - 14.1.0
