overrideScripts:
  "generate:ghinfo": "node --experimental-specifier-resolution=node bin/ghinfo.js generate -d media -t utils"
  "build:ts": "rimraf lib && tsc --extendedDiagnostics && node scripts/esm-post-process.js"

ignoreDependencies: ["ghinfo"]
